// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use diesel::prelude::{Insertable, Queryable};
use diesel::{Selectable, SelectableHelper};
use diesel_async::pooled_connection::{AsyncDieselConnectionManager, bb8::{Pool, PooledConnection}};
use diesel_async::{RunQueryDsl, AsyncPgConnection};
use uuid::Uuid;
use chrono::DateTime;
use chrono::offset::Utc;
use crate::schema::subscriptions;

#[derive(Queryable, Selectable)]
#[diesel(table_name = crate::schema::subscriptions)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Subscription {
    pub id: Uuid,
    pub email: String,
    pub name: String,
    pub subscribed_at: DateTime<Utc>,
}

#[derive(Insertable)]
#[diesel(table_name = crate::schema::subscriptions)]
pub struct NewSubscription<'a> {
    pub id: &'a Uuid,
    pub email: &'a str,
    pub name: &'a str,
    pub subscribed_at: &'a DateTime<Utc>,
}

pub async fn create_subscription(connection_pool: &Pool<AsyncPgConnection>, email: &str, name: &str) {
    let id = &Uuid::new_v4();
    let new_subscription = NewSubscription { id, email, name, subscribed_at: &Utc::now() };
    let mut connection = connection_pool.get().await.unwrap();

    let subscription = diesel::insert_into(subscriptions::table)
        .values(&new_subscription)
        .returning(Subscription::as_returning())
        .get_result(&mut connection)
        .await
        .expect("Error saving new subcription");
}
